version: '3.8'

services:
  qr-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3880:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: npm start 